[core]
	######   For Windows   ######
	;sshCommand = ssh
	;editor = 'code' --wait
	;autocrlf = true
	######   For Msys2   ######
	;sshCommand = ssh
	;editor = 'code' --wait
	;autocrlf = true
	######   For WSL   ######
	;sshCommand = ssh
	;editor = 'code' --wait
	;autocrlf = input
	######   For Linux   ######
	;sshCommand = ssh
	;editor = ''
	;autocrlf = input
	######   For Mac   ######
	;sshCommand = ssh
	;editor = ''
	;autocrlf = input
	######   For BSD   ######
	;sshCommand = ssh
	;editor = ''
	;autocrlf = input
[credential]
	helper = wincred|osxkeychain|manager
[user]
	name = Church1776
	email = brassmajor@gmail.com
[alias]
	br = branch
	cf = config
	cfg = config --global
	cfs = config --system
	ck = "!f() { git checkout \"$@\" >/dev/null || return; git status -sbu; git status --show-stash --porcelain=v2 | sed '/stash/!d'; }; f"
	cm = commit -m
	df = diff HEAD
	drop = restore --staged
	ds = diff --staged
	du = diff
	graph = log --graph --decorate --full-diff --stat --patch
	list = log --oneline --decorate
	mg = merge
	mgff = merge --ff-only
	mod = submodule
	patch = add --patch
	pick = cherry-pick
	pl = pull
	ps = push
	rb = rebase
	rbff = rebase --ff-only
	rs = reset
	st = "!f() { git status -sbu \"$@\" || return; git status --show-stash --porcelain=v2 | sed '/stash/!d'; }; f"
	sw = "!f() { git switch \"$@\" >/dev/null || return; git status -sbu; git status --show-stash --porcelain=v2 | sed '/stash/!d'; }; f"
	unstage = restore --staged
[filter "lfs"]
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
[init]
	defaultBranch = master
